### ISSUE TITLE
Can we start using generators / iterations?

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#590]
now with iojs and node v0.11, we can start using iterators and generators.  This makes for simpler and clearer programming. 

However, this means you cannot run actionhero on older versions of node. 

Is it worth it?

**Comment by neilstuartcraig** [comment]
I'm torn between wanting to support progress and making life difficult for new users. 
I guess since iojs is installable via nvm now that's probably not too much of an issue but eg my machine is still on node 0.10.x so I'd have to install iojs. 
I guess it's a good prompt for people to upgrade but might cause folk with ah in prod some heafacjes

**Comment by crrobinson14** [comment]
Why not make ActionHero 11 line up with Node 11? Put the generators there. I really like them but they're "candy", not "oatmeal".

**Comment by omichowdhury** [comment]
Our staging/production env runs on AWS Elastic Beanstalk's node.js, which currently has support for the following versions:
```[0.8.26, 0.8.28, 0.10.21, 0.10.26, 0.10.31]```

It's a real bummer that Amazon have not updated node support since August but hopefully they'll get a kick now that a new major stable version is out. We'll see and we may kick EBS to the kerb if this doesn't improve.

**Comment by neilstuartcraig** [comment]
Ah. That's definitely worthy of strong consideration then. 

I'll see the aws folk this week at work hopefully so I'll hassle them about it and see if there's a timeline on it.

**Comment by slattery** [comment]
Just a drive-by, sorry, but the elevenses sync (AH<->node/io) makes sense to me!

**Comment by omichowdhury** [comment]
@slattery io.js is actually at 1.3.0 now because it uses semver and node.js does not. I see no reason to tie AH's versioning to anything other than its own changes since it also uses semver (correct me if I'm wrong @evantahler). Cookie to the first project that gets to 100.x

**Comment by slattery** [comment]
@omichowdury, good point.  It is instructive and correct to highlight semver use/disuse there.      

I’ll rephrase and say that 

1. the changes proposed here are probably considered semver Major, and therefore anyone having to support io and node10 will have a clear direction in terms of their own installs.

2. The poetry with 11:11 there was too good to pass up, so cheers to both @crrobinson14 and yourself...

**Comment by omichowdhury** [comment]
Poetry++
I propose a haiku as our versioning system.
First line changed? Major.
Second? Minor, new features!
Third? Chill, just a patch.
You'll know what changed by reading the new version. Now that's semantic versioning.

**Comment by evantahler** [comment]
Lol!

Yes, I try to keep the semver rules in place (break = major, new features = minor).  I was pretty lax about it pre v7.0.0 or so... but I learned!

**Comment by paulxtiseo** [comment]
I would actually recommend forking AH into a separate AH2 cod, ase ,and slowly transitioning AH1 into a maintenance-like mode with little functionality changes for the projects that cannot migrate quickly for whatever reason.

**Comment by crrobinson14** [comment]
Why the fork? Forks are great if you think you're going to change your mind, but it's not like the old versions are going away. The whole point of NPM and semver is to allow old clients to continue with what they have, and those that are prepared to upgrade can do so.

Some projects fork to make it easy to maintain old versions - but the fix:feature ratio for AH is very low if you look at recent commits...

Another option would be for people who want to stay on the old code tree to make the forks themselves...

**Comment by paulxtiseo** [comment]
@crrobinson14 I suggest (humbly! :) ) that if AH wants to make new or improved functionality available to everyone, yet wants to migrate the platform to ES6, there is an inherent fork in the road, isn't there? Either you choose to make your new/improved stuff available to all (ES6 and non-ES6 end users) and that requires mutually-incompatible code diffs, or only to ES6-friendly end users.

**Comment by crrobinson14** [comment]
@paulxtiseo I don't disagree. It's just that the trend in the project has been to follow semver, where an in-project branch and major build number did the same thing. If it's going to be embraced by the core project, forks get complicated when people want to contribute because it's not always clear what to fork from and how to stay up to date. This is all personal opinion, of course. Just tossing in my 2c. Ultimately it's Evan's call.

**Comment by evantahler** [comment]
What I guess we really need to do is take a poll:

- what version of node are you on
- are you *able* to upgrade your node version or boot your app with --harmony flags?
- will moving to generators make you unable to use actionhero?

The big issue here is how you deploy.  If you are heroku, you can use iojs.  If you are on elastic beanstalk, you can't.

**Comment by evantahler** [comment]
... how do we run a good survey?

**Comment by paulxtiseo** [comment]
QuestionPro or SurveyGizmo. The former may have good, free service for projects like yours if you talk to them. Lots of free, open poll options if you google for it...

**Comment by omichowdhury** [comment]
Amazon [released](http://aws.amazon.com/about-aws/whats-new/2015/03/aws-elastic-beanstalk-supports-docker-1-5-ruby-2-2-and-nodejs-0-12-0/) 0.12 support on Elastic Beanstalk last week.

So any reasons left to stick with 0.10.x?

**Comment by omichowdhury** [comment]
Well this post by Eran Hammer advocates sticking with 0.10:
http://hueniverse.com/2015/03/02/the-node-version-dilemma/

**Comment by heavyk** [comment]
btw you can use generators now... I will give an example using our sign-in script (forgive the livescript)

```ls
require! \genny
action = (gen) ->
	fn = genny.fn gen
	(api, connection, next) ->
		fn api, connection, (err, res) ->
			if err
				connection.error = err.stack
				res = true
			next connection, !!res

export sign-in =
	name: "sign-in"
	description: "I am sign in"
	inputs:
		ident:
			required: true
			min: 4
			max: 100
			validator: (v) ->
				if v.length >= 4 then true
				else throw new Error "ident must be between 4 and 100 characters"
		password:
			required: true
			min: 4
			max: 100
			validator: (v) ->
				if v.length >= 4 then true
				else throw new Error "password must have 4 and 100 characters"
	authenticated: false
	version: 1.0
	run: action sign-in = (api, connection, resume) ->*
		# `yield from` -> yield*
		dd = yield from api.identities.sign-in connection.params.ident,
			connection.params.password,
			resume.gen!
		# passing resume.gen() allows you to use other node-style callbacks in the resulting generator
		# ...
		connection.response.data = dd
		return true
```

then, `api.identities.signIn` looks like this:

```ls
sign-in: (ident, password, resume) ->*
	hashword = @hashword password
	unless identity = yield api.mongo.db.identities.find-one { ident, hashword }
		throw new Error "could not authenticate identity #ident"
	sess = yield api.identities.session.create {
		# ...
	}, resume!
	return sess
```

use https://github.com/spion/genny ... it's da bomb :+1:

as you can see, if any error is thrown inside of the generator, it'll be picked up automatically and put in `connection.error` the `action` function at the very top

**Comment by evantahler** [comment]
Moved to the v12 milestone...

**Comment by evantahler** [comment]
As of now (Dec 2015), over 50% of "commercial node.js projects" run v0.10.x

https://semaphoreci.com/blog/2015/12/15/nodejs-version-usage-in-commercial-projects-2015-edition.html

**Comment by wasd171** [comment]
So the other ~ 45% of "commercial node.js projects" running > v0.10.x with at least v0.12.x having significant 25% is not enough?

It would be really great to start using all modern features, they make life a lot easier.

**Comment by evantahler** [comment]
I'm confused.  

Node is backwards compatible.  Because we want to support the majority, actionhero core will run on node v0.10 for now.  That said, actionhero will work on every version of node/ioJS upwards.  While the core doesn't use any of the modern features, you can certainly use them within your actions/tasks/initializers if you now the version of node which you run on will locked.

**Comment by wasd171** [comment]
Actually I wrote it due to [this pull request](https://github.com/evantahler/actionhero/pull/692). AH could at least be more friendly for Babel users :)

Anyway, I found a solution:

One needs to create `index.js` with the following
```
require("babel-register")({
	ignore: /(redis\.js|node_modules)/
});

require("actionhero/bin/actionhero");
```

It forces Babel to skip `redis.js` and every file from `node_modules`, loading them the usual way.

Then running `node .` instead of `actionhero start` would do the trick

BTW, thanks for great tool!

**Comment by evantahler** [comment]
Ah, so the issues are with `transpilers` and not ES6 at all... which, if you were really using ES6 all the way though, you wouldn't need?

Anyway, that note for Babel is really good!   Can you open a PR to add this to the documentation?  Probably in the `running-actionhero` section

**Comment by crrobinson14** [comment]
Just a data point: using AH 12.2.3 here on NodeJS 4.2.3 which includes v8 4.5.103.35 (`node -p process.versions.v8`). We're successfully using a bunch of the ES6 "staging" features included in NodeJS without using the Harmony flag or a transpiler, including block scoping, Object.assign (very handy), etc. It's a good combination.

I'm not in any way suggestion that Babel users don't have a point, but I'm PERSONALLY not a fan of the transpiler approach for the same reason I'm not a huge fan of CoffeeScript. In the end, the code will "run" as whatever is natively supported - so that's where you have to optimize, debug, etc. I prefer not to think in one language and debug in another. It doesn't feel like these new features are so far off that I can't wait until 2016 for the bulk of them.

Just my own personal opinion, FWIW.

**Comment by evantahler** [comment]
Many of our dependent package (ws, qs, etc) have stated that they will start only supporting node `>=4.0.0` going forward.  That means we need to start doing the same.

Version 13 of actionhero will target only `>= v4.0.0`... which will make this more of a reality.
