### ISSUE TITLE
Execute tasks on running Actionhero server from CLI

### ISSUE THREAD

**Issue by ndcollins** [evantahler/actionhero#608]
Perhaps there already is a way to do this, but I would like to be able to execute a task from the CLI using something like

actionhero exectuteTask -name="MyTaskName"

If we had that in place, we could have more control over the scheduled execution of tasks by being able to execute them from CRON or Heroku Scheduler or the like.

**Comment by evantahler** [comment]
That's not really how the task system works.  You could write a grunt task to `enqueue` a task, or you could boot another actionhero server to act as a `worker` (with or without a specific work queue), but executing a task in-line is not something you should be able to do.   Can you talk more about your use case?

You can read up on how https://github.com/resque/resque and our fork, https://github.com/taskrabbit/node-resque work regarding enqueuing and workers.

**Comment by ndcollins** [comment]
For my use case I have some batch processes that need to execute where it needs to recursively GET data from an external API, manipulate it, then PUT the updated data back to the external API. This process takes an hour or two, so I'd like to schedule it to run every evening during off hours, so starting at 1am, for example. With the current system, and correct me if I'm misunderstanding it, but it appears that you can only set the interval at which a task runs, not a specific start time.

**Comment by evantahler** [comment]
The way to handle this properly is a 2-phase approach.    Have a recurring
task run each and every minute.  Have that task check what time it is, and
if it is the proper time, then enqueue a second task (that long one you
mention).  You can start doing fancy thing with that first task, like use
api.cache to store the last time it ran, how long it takes, etc.

Again, you don't want to rely on actual "cron" or something similar because
it makes one server more "important" than the rest.  You can't destroy it,
you can't scale it, etc.

--
 Evan Tahler | evantahler@gmail.com | 412.897.6361
 evantahler.com | actionherojs.com

**Comment by evantahler** [comment]
Closing this issue.

Another approach would be, of course, to just create an action that enqueues the task you want.  You can then `curl` it (probably with authentication).
