### ISSUE TITLE
v11.5.0 breaks if custom error serializers are not defined

### ISSUE THREAD

**Issue by bakavic** [evantahler/actionhero#671]
The [release notes](https://github.com/evantahler/actionhero/releases/tag/v11.5.0) don't mention that `config/errors.js` needs to be updated.

This results in actions ending with user errors throwing 
```
Uncaught TypeError: Cannot read property 'servers' of undefined
````
which is not very clear what caused it.

This change can be counted as not particularly backward-compatible?

**Comment by evantahler** [comment]
Good catch.  
The system *should* be sourcing any undefined config variables from within the package, but that might not be working.

**Comment by evantahler** [comment]
ahh! Yes, the default config merge behavior doesn't work here because we are telling the [config loader] not to expand these keys(https://github.com/evantahler/actionhero/blob/master/config/errors.js#L7), as it would mess up the functions for the error strings.

I *think*, as far as semver is concerned, requiring a config change (and no other code change) is OK for a 'medium' version bump?  Either way, I'll update the release notes.
