### ISSUE TITLE
New Socket without remotePort?

### ISSUE THREAD

**Issue by mstdokumaci** [evantahler/actionhero#675]
I'm seeing a stacktrace like this at my production server:
```
.../actionhero/initializers/connections.js:103
        if(data[req] === null || data[req] === undefined){ throw new Error(req
                                                                 ^
Error: remotePort is required to create a new connection object
    at .../actionhero/initializers/connections.js:103:66
    at Array.forEach (native)
    at api.connection.setup (.../actionhero/initializers/connections.js:102:59)
    at new api.connection (.../actionhero/initializers/connections.js:80:12)
    at api.genericServer.buildConnection (.../actionhero/initializers/genericServer.js:56:24)
    at handleConnection (.../actionhero/servers/socket.js:200:12)
    at Server.<anonymous> (.../actionhero/servers/socket.js:43:9)
    at Server.emit (events.js:107:17)
    at TCP.onconnection (net.js:1330:8)
```

This is one of 3 appservers behind HAProxy. I didn't run it in cluster mode because this error was not visible in logs, only dead worker notifications. So I ran them with "nmp start" and came to this error at console after some days. Any clue why it happens?

**Comment by evantahler** [comment]
Can you share more information:
- action hero version
- type of connection (http? websocket?)
- haproxy settings?
- bridge between haproxy and actionhero (sockets, http, etc)

Basically this happens when you are trying to have a client connect to action hero, but no information about the connection can be determined (like the incoming ip adress)

**Comment by mstdokumaci** [comment]
- actionhero 11.5.1
- tcp socket only (not websocket)
- haproxy settings here:
```
listen game
        mode tcp
        bind :5000 ssl crt ...
        log global
        option log-health-checks
        option tcplog
        option tcpka
        timeout client 3600s
        timeout server 3600s
        timeout queue 5s
        timeout connect 5s
        maxconn 100000
        server app1 app1:5000 check on-marked-down shutdown-sessions
        server app2 app2:5000 check on-marked-down shutdown-sessions
        server app3 app3:5000 check on-marked-down shutdown-sessions
        server maintenance 127.0.0.1:15000 backup
```
- haproxy and app servers are on same local network. app1, app2 and app3 are aliases for local 10.something ips written in hosts file.

**Comment by evantahler** [comment]
Yeah, that all looks fine...

Since you have SSL options, all assume you are running the socket server with `secure=true`, so that's a [TLS server](https://nodejs.org/api/tls.html).  I can't find anywhere in the documentation which mentions that [remotePort](https://nodejs.org/api/tls.html#tls_tlssocket_remoteport) would ever be undefined.   It might be that you have connections coming and then disconnecting so quickly that by the time node attempts to access the TCP stream, the client has already disconnected.  There are not async callbacks within the stack from when a connection is created (it's processed in linear time), so it is unlikely, but possible, especially if your server is doing other CPU-intensive things at the time of the connection's instantiation, so the processing of the connection would be delayed.  Do some checks on your CPU utilization by node when you are seeing this error.

This is a tricky error to handle, as there is not a valid client yet to send the error too, so the server does the only thing it can, and crashes with an error thrown.

**Comment by mstdokumaci** [comment]
actionhero socket server is not secure actually.
ssl connection is terminated at haproxy loadbalancer and connectin from haproxy to app servers are insecure. they are already in same local network.
our mobile app is still waiting for review at itunes so servers are not loaded in any way yet. there is a connection middleware making a redis call but that function has no callbacks so can not be blocking i guess.
how can i workaround this thing until we discover the real reason, without ignoring all other errors. can you think of an elegant way?

**Comment by evantahler** [comment]
This would be the work-around: https://github.com/evantahler/actionhero/compare/enforceConnectionProperties?expand=1

**Comment by mstdokumaci** [comment]
With same setup I've seen this trace at one of app servers today. Cluster seems stopped working with no reason. Nothing I can see in logs. Might this be because of a weird behaviour of HAProxy?
```
notice: cluster complete, Bye!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: channel closed
    at ChildProcess.target.send (child_process.js:414:26)
    at sendHelper (cluster.js:676:8)
    at RoundRobinHandle.handoff (cluster.js:198:3)
    at RoundRobinHandle.distribute (cluster.js:184:20)
```

**Comment by evantahler** [comment]
This looks more like an issue with the host you are running actionhero on.  The `channel closed` error happens when one of the children dies in a non-standard way (kill -9 for example) and doesn't have the time/ram/disk to gracefully shutdown properly.

**Comment by evantahler** [comment]
Closing for now... let me know if you learn any more information
