### ISSUE TITLE
Locks just not works

### ISSUE THREAD

**Issue by SDSWanderer** [evantahler/actionhero#695]
May be I missed something, but I really don't understand how locks can work based on non-atomis redis operations. For fix this issue in my app, I write own lock implementatation based on redis `incr` command. Here simple test that failed besause of this issue:

```javascript
process.env.NODE_ENV = 'test';

var should = require('should');
var actionheroPrototype = require('actionhero').actionheroPrototype;
var actionhero = new actionheroPrototype();
var api;

describe('actionhero lock bug', function(){

  before(function(done){
    actionhero.start(function(err, a){
      api = a;
      done();
    })
  });

  after(function(done){
    actionhero.stop(function(err){
      done();
    });
  })

  it('Should be only one lock OK', function(done){
    var locksRetrieved = 0;
    var locksRejected  = 0;

    var concurentLocksCount = 10;

    for (var i = 0; i < concurentLocksCount; i++) {
        api.cache.checkLock('test', 10, function(error, lockOk) {
          if (lockOk) {
            locksRetrieved++;
          } else {
            locksRejected++;
          }

          if ( locksRetrieved + locksRejected == concurentLocksCount) {
            locksRetrieved.should.be.equal(1); // Only first atempt
            locksRejected.should.be.equal(concurentLocksCount - 1); // Everything else
            done();
          }

        });
    }
  });

});
```

**Comment by evantahler** [comment]
I think you might be misunderstanding how the locking mechanism works:

1) These locks are to ensure that only one actionhero *instance* works with a cache object at given time.  Any given server (like you have in your test) can modify the object as many times as it wants.  This means that the same server asking `checkLock` will always get `ok`
2) There is an atomic check to *create* the lock, which will fail if the object is already locked.  This is handed in the `api.cache.lock` method via `redis.setnx`.  Your test never actually locks anything, so *checking* the lock repeatably will always yield `ok`

I took your test case and corrected it so that:
- you change "server names" each test to emulate accessing the lock from other actionhero instances
- you lock the object the first time obtain the lock so that there is something to test against

https://github.com/evantahler/actionhero/commit/2e8e59a2b470311471860e6752194886e4eae196
