### ISSUE TITLE
actionhero loads this plugin incorrectly?

### ISSUE THREAD

**Issue by l0oky** [evantahler/actionhero#715]
Strange bug, [*ah-jwtauth2-plugin*](https://github.com/ifavo/ah-jwtauth-plugin/) appears not to have Its main object `api.jwtauth` defined. At first I thought It has to be something wrong with the plugin, but I couldn't find whats wrong with It. I managed to get the plugin working by following [these reproduced steps](https://github.com/l0oky/plugin-load-bug). And I didn't even tamper with the plugin at all.

This is maybe occurring because the way *actionhero* loads the plugins at application start.

**Comment by evantahler** [comment]
There's nothing wrong with actionhero here.  

The `ah-jwtauth2-plugin` plugin creates its namespace within the `start` method.   You are trying to access it within your own plugin within an `initialize` method.  

All `initialize` steps happen before `start` steps.  

I would argue since `ah-jwtauth2-plugin` is simply creating helper methods (and not connecting to a database or anything) that it should move its setup steps to `initialize`.  Open an issue on that project.  

To make your initializer work, just move your stuff to `start` with a priority greater than 1000 so that JTW will be loaded ahead of time

**Comment by evantahler** [comment]
Initializer documentation for reference: http://www.actionherojs.com/docs/#initializers
