### ISSUE TITLE
Support for plugin auto-registration

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#727]
- is listing a plugin within node-modules enough?  Should we just scan that directory?

**Comment by slattery** [comment]
Do you mean match for ah-{pluginname}-plugin in node_modules?  That would be nice.

**Comment by l0oky** [comment]
Makes sense, since you have a naming convention for plugins.

**Comment by neilstuartcraig** [comment]
I have some code for at least part of this already. The difficulty currently is inserting into the plugins.js conf file. It'd be nice and f the format of that file was JSON or could include an external chunk of JSON, otherwise were down to clunky string replacement which is bad news for all but brand new, untouched config files

**Comment by l0oky** [comment]
The `nested plugin` needs to be instantiated in conformity with main ah project priorities. To do that i think we need to redesign the priority system in actionhero so instead of expressing plugin priority in numbers we express it by order. For example : 
```
// Instead of expressing priority like this:
ah-plugin-database priority = 1
ah-plugin-1 priority = 1000
ah-plugin-2 priority = 1000
ah-plugin-3 priority = 1000
// We express it like this:
ah-plugin-database priority ->
ah-plugin-1 priority<->
ah-plugin-2 priority<->
ah-plugin-3 priority
//  -> meaning higher priority than everything that is following; 
// <-> meaning same priority as the following
```
This expression is just a concept we could make it a `plugins.json` file for example or something like that.

**Comment by evantahler** [comment]
I think the proposal here is to actually remove `config/plugins.json` entirely.  If we start `api.config.general.paths.plugin = []`, than it would be an explicit declaration to change that to include `./node_modules` and any other folder you want.  This means that anything you've installed via NPM was *meant* to be a plugin.    

From there, we just need a convention on how to make a folder "appear" as a plugin (so we don't try to load normal packages you might want within your project), and there are couple of options to do so:

- lazy-scan the directory for folders called "actions" and "tasks".
  - I think this will create too many false positives.
- scan all package.json files within node_modules for something custom, like `isActionheroPlugin: true`
- scan all directories within node_modules for a custom file, something like `isActionheroPlugin.json`
- ... other thoughts?

**Comment by slattery** [comment]
Thanks Evan and everyone for having this conversation.   Plugins are very valuable!   They shape the way I approach dev and deployment.  Even if you remove chat and tasks - plugins and the way AH homogenizes different connection types makes AH super super helpful.

On this immediate topic of discovery, there is the naming convention for starters and I would think that has to remain the first condition in any search. 

Regarding subdirs, with content plugins and some others I have no actions folder.  Some only need initializers to provide middleware or to log and display which git branch is loading for plugins in development.

To step back a sec, there are two features (intentional or not) I wanted to highlight.   I would need to preserve or workaround them in an auto-reg system.  They are ability to ignore plugins on the file system and the ability to direct load order.

I like having the ability to load a subset of plugins if I ship a number of plugins in an archive or VM etc.  So that might mean a convention in each plugin's config like an 'enable' field?

I have plugins that simply exist to deliver content, and I use the load order to overlap and serve the 'last entity in the stack' when naming files in the public folders.

Cheers everyone,
Mike

**Comment by neilstuartcraig** [comment]
My vote would be for a JSON file in each plugin package directory which held some plugin info. I would image there's other stuff we could put in there too like plugin loading order ( which could perhaps be overridden by the plugin config, if set).

**Comment by evantahler** [comment]
oh, I like that @neilstuartcraig.  We could do something like:

```js
// from /my_plugin/actionheroPlugin.js
exports.plugin = {
  autoload: true,
  priority: 1000
}
```

**Comment by neilstuartcraig** [comment]
@evantahler - yep, exactly. Then ideally there'd be an include, source controllable JSON file in the project files which could override any or all of it. Something along those lines anyway. My main request would be that I can create a automateable file which can be source controlled.

**Comment by evantahler** [comment]
Can you share an example of what would live in the top level project?  So... `plugins.js` would now only contain overrides?

```js
// config/plugins.js
exports.default = {
  general: function(api)
  {
    return {
      // these are overrides to the plugin settings within each plugin
      plugins: {
         'my-awesome-plugin': {  priority: 1 }
      }
    };
  }
};
```

**Comment by l0oky** [comment]
Plugin order could be made like an expression higher than, equal to. For example : 
```javascript
{
/... 
 plugins:{ 
  'ah-databaseconnector-plugin': { priority: '<' },  // Highest priority
  'ah-awesome2-plugin': { priority: '<' }, // Lower priority then the first
  'ah-awesome3-plugin': { priority: '=' }, // Same priority as the previous
  'ah-awesome4-plugin': { priority: '=' }, // Same priority as the previous
  'ah-awesome5-plugin': { priority: '<' }, // Lower priority then the previous five plugins
  'ah-awesome6-plugin': { priority: '=' }, // Same priority as the previous
 }
}
```
I used the < sign since the lower the number the higher the priority ( which is a bit counter-intuitive ) but oh well.

**Comment by neilstuartcraig** [comment]
Or, just a suggestion - it could have system d style deps where each plugin could state other plugins on which it depends (ie it should be loaded after its deps). This means you don't need numeric priorities at all which makes things simpler in some cases. 
And/or we could have the principle of something akin to UNIX run levels. I'm thinking of perhaps 5-10 which could be labelled (either by custom or default) and could be broad levels eg "data layer". 
Just a couple of ideas for the pot.

**Comment by l0oky** [comment]
@neilstuartcraig Yeah that one is better I think. But don't ask me, I don't really know why there are numeric priorities at the first place. In the chat I suggested that priorities stay hidden from the developer and let each initializer have Its own dependency like you mentioned, developer should not worry about changing priority numbers.

**Comment by evantahler** [comment]
So here's a wacky idea which would would greatly simplify both plugin registration and nesting (https://github.com/evantahler/actionhero/issues/726): symlinks.

- Say I want to include `ah-plugun-A` in my project, which contains some actions and an initializer. 
- I `npm install --save ah-plugun-A` into my project as I normally would.  
- rather than add the plugin to my `config/plugins.js` lists, I now would run a new command `actionhero source ah-plugun-A`.
- This new command would search all paths listed within `api.config.general.paths.plugin` for a directory called `ah-plugun-A`.  Once it finds it, it would then create symlinks from the plugin into my project's top-level directories.
  - For example, I would have the following for the actions in the plugin: `/actions/ah-plugun-A ---> /../node_modules/ah-plugun-A/actions`

This symlink method has a few awesome side effects:
- There is no longer a need to maintain a list of plugins anywhere in the project
- This creates an incredibly clear mapping of what plugins are active in a project, as the symlink is visible in the directory. 
- We could now do 'partial' plugin includes.  Only want the actions and not the initializer from a plugin?  Delete that symlink.  Only want some of the actions?  Don't symlink the whole directory in then... just link some of the actions
- This also greatly simplifies the `configLoader`, as we no longer need to have any special code for plugins at all!  We already support sub-directories, which (should) already cover symlinks.  

This solves the nested plugin problem as well.  If `ah-plugin-A` relied on `ah-plugin-B`, the plugin would have included `ah-plugin-B` via npm, and have already sourced it.  This means that `ah-plugin-A` would *already* have a symlink in its own `/actions` or `/initializers` directories.  This would chain back to the project top level which would then include all the needed files.

**downside:** Windows users.  Frankly, I'm willing to launch this feature without windows support for now and let that OS catch up later.

**Comment by l0oky** [comment]
Good thing I just moved to debian. :)

**Comment by neilstuartcraig** [comment]
Sounds great @evantahler. My personal preference is for something which can be automated, which this clearly can so its great and the re-use of existing tech is a bonus, always up for complexity reduction. 
I don't see why it wouldn't work on Windows - provided the symlinks are made via cross platform libs then I think it's work...or is my tired brainbox missing something? :-)

**Comment by hutchike** [comment]
Looks like it might work on Windows too:
https://en.wikipedia.org/wiki/NTFS_symbolic_link

**Comment by AngeloR** [comment]
There are scenarios where symbolic links break on windows, (IE: if you are developing in a vagrant box, it doesn't support symlinks within directories shared with a windows host). However, I think forgoing windows support may be a good idea in order to get this functionality in. 

However, what would happen in the case of two plugins requiring two different versions of the same plugin?

**Comment by evantahler** [comment]
NPM already handles this with its semver mapping! Check out #1 here: http://blog.izs.me/post/1675072029/10-cool-things-you-probably-didnt-realize-npm

So basically each plugin's dependancies would be inside of its own node_modules and we would link all the way down.  I haven't tested it yet, but I think it would work out.

**Comment by hutchike** [comment]
FWIW I think it's a great idea. Elegance wins, and so does leveraging npm.

**Comment by evantahler** [comment]
Cool.  Closing this issue in favor of this PR https://github.com/evantahler/actionhero/pull/758.
Move the conversation over there!
