### ISSUE TITLE
js reserved keyword

### ISSUE THREAD

**Issue by synthmeat** [evantahler/actionhero#740]
```package``` is a JavaScript reserved keyword.

https://github.com/evantahler/actionhero/blob/master/config/redis.js#L32

Alterntives: ```pkg```, ```lib```, ```library```...?

**Comment by evantahler** [comment]
We've talked about this before here: https://github.com/evantahler/actionhero/pull/692
As far as we could tell at the time, `package` was not a reserved keyword in javascript, but only in some transpilers like babel.  Since that was the case (as far as we could tell), we ignored it at the time.  

Since we cutting a new major version release soon, this would be the right time to change this.  `pkg` seems fine to me.  You'll need to change that within this project and within [node-resque](https://github.com/taskrabbit/node-resque)

**Comment by synthmeat** [comment]
It was reserved as far as es2. https://mathiasbynens.be/notes/reserved-keywords

Ok, forking and fixing here and in node-resque...

**Comment by evantahler** [comment]
Awesome, thanks!  
I'm happy to cut a new version of node-resque as well for this.

**Comment by evantahler** [comment]
solved via:
- https://github.com/evantahler/actionhero/pull/746
- https://github.com/taskrabbit/node-resque/pull/113
