### ISSUE TITLE
Function references in plugin configs get called multiple times during startup

### ISSUE THREAD

**Issue by leaanthony** [evantahler/actionhero#759]
It looks like function references within plugin config files are getting called during server startup and their value saved against the original key. Actionhero version: 12.5.0 tested.

## Steps to reproduce
* npm install actionhero
* actionhero generate
* Create config/plugins/myTest.js
```
function myFunction() {
  console.log("I've been called");
  return "it's just a flesh wound!";
}

exports.default = {
  "myTest": function (api) {
    return {
      test: myFunction
    }
  }
};
```
* Create actions/myTest.js
```
exports.action = {
  name: 'myTest',
  description: 'config test',
  run: function(api, data, next){
    data.response = api.config['myTest'].test;
    next();
  }
};
```
* actionhero start
```
$ actionhero start
info: actionhero >> start
I've been called
I've been called
I've been called
I've been called
2016-01-21T09:39:02.727Z - notice: *** starting actionhero ***
```
* Test action:
```
$ curl -k http://localhost:8080/api/myTest
"It's just a flesh wound!"
```
* I thought it might be a feature of require, so I tried this Node.js test:
```
$ node
> var test = require("./config/plugins/myTest")
undefined
> test.default.myTest().test
[Function: myFunction]
```
...which seems to work as expected. 

Thanks.

**Comment by evantahler** [comment]
Yep, that's exactly what happens! Glad to see you are getting into the weeds :D

We do this because we can't guarantee config load order, and one config file should be allowed to refer to the data within another.  The best example of this is how by default the [`task` config](https://github.com/evantahler/actionhero/blob/master/config/tasks.js#L45) refers to the `redis config` in the default case.  Generically, since we can't be sure which one will be loaded first (especially when plugins are involved), we basically try to source the config n times each time we get to an undefined object. The code for this is here: https://github.com/evantahler/actionhero/blob/master/initializers/configLoader.js#L106-L128

Since this is expected behavior, and if you need a method to really only be called one, you have a few options:
- tools like [once](https://www.npmjs.com/package/once) exist for this kind of thing
- since you know these are sync (linear-time) functions, it would be safe to set a blocking bit in the scope of the config file, ie:

```js
var functionRan= false;

function myFunction() {
  if(!functionRan){
    console.log("I've been called");
    return "it's just a flesh wound!";
    functionRan = true;
  }
}

exports.default = {
  "myTest": function (api) {
    return {
      test: myFunction
    }
  }
};
```

**Comment by leaanthony** [comment]
Thanks for clarifying this. I was looking at the potential of being able to hook functions into the config so that they may be customized at the server level rather than digging down into the bowels of the plugin itself. EG:
```
var utils = require('myCustomLib');

exports.default = {
  "myTest": function (api) {
    return {
      utils: utils
    }
  }
};
```
This may actually not be the approach I want to take, I'm just feeling out the boundaries.
