### ISSUE TITLE
Use whiteboard rather than slate for docs (keep it all Node)

### ISSUE THREAD

**Issue by evantahler** [evantahler/actionhero#763]
https://github.com/mpociot/whiteboard

**Comment by n-s-k** [comment]
+1

**Comment by l0oky** [comment]
:+1:

**Comment by evantahler** [comment]
the tool currently doesn't support multiple themes, which we need now to run both the docs and 'common' site in one build.  Ya'll remember to check back in a bit and see if they progress!

**Comment by mpociot** [comment]
Can you tell me the current process using slate?
How do you use multiple themes?

I'll see if I can implement it into whiteboard.

**Comment by evantahler** [comment]
Thanks @mpociot, we'll give it a shot!

**Comment by evantahler** [comment]
@n-s-k is this something you can work on?

**Comment by synthmeat** [comment]
@evantahler I'm game for this, now that style is in order. Was to go through docs properly now anyways.

**Comment by evantahler** [comment]
Awesome!
Let me know how I can help

**Comment by synthmeat** [comment]
@evantahler Well, I *would* like to discuss:
- possibility of moving site (with docs) to separate repo
- ignoring [whiteboard](https://github.com/mpociot/whiteboard) since it is:
  - not an npm module
  - just styles and scripts ripped from Slate
  - a very thin wrapper around [hexo](https://github.com/hexojs/hexo), static generator

I personally didn't like Slate, for just one reason though - couldn't open chapters on the left in new tabs.  Hexo itself is a good choice, and can handle entire site, including docs, as can be seen [here](https://github.com/hexojs/site), has bajillion plugins, and is regulary maintained for quite a while now.

Site could still be included as submodule within ActionHero repo itself if that's found useful, though then it couldn't be versioned differently between branches (to my knowledge).

**Comment by evantahler** [comment]
There were a few reasons to have the docs *within* the same repo as the code:

- you can commit new code and the related docs in the same PR
  - you won't forget to write docs either!
- we can tie the building/publishing of the site to [`npm publish`](https://github.com/evantahler/actionhero/blob/master/package.json#L70-L71) so new docs go out with new code
- you can always reference the historical state of the docs within the context of historical code (if you view the tag for v13, you'll see the docs for the same version)
- if you have the code locally, you have the docs locally.

To that end, for now, I want to keep the docs within the core repo.  As the project gets bigger, and we have more "release management", we can revisit this.

As far as changing the site over to some other build/template/server system, have at it!   I like the 3-column layout of whiteboard, but there are plenty of other options.  As long as both words and code can be viewed side-by-side I'm game.

The only real requirement is that the site should compile to static assets so we can continue to host the thing on github pages.

**Comment by gcoonrod** [comment]
Should this still be open? @evantahler

**Comment by evantahler** [comment]
I guess not!
