### ISSUE TITLE
Extending core servers

### ISSUE THREAD

**Issue by TombolaShepless** [evantahler/actionhero#816]
Apologies if this is obvious, but I have looked at the source, issues and docs but can't see any way to achieve this. The only issue that is related to my question is [here](https://github.com/evantahler/actionhero/issues/71) but this is over three years old and it looks like the API has changed a lot since then.

I would like to "decorate" the `sendMessage` function for all servers in order to modify every response to clients. I have tried implementing action middleware to achieve this but noticed that `connection.sendMessage()` (to send a single message to a single connection) never passes through the middleware, meaning I'd have to duplicate the middleware logic in multiple places. IS there some sort of "server middleware" I'm not aware of?

An aside question: Is it possible to disable the "bye" message also? Similar to the `sendWelcomeMessage` option?

Again, sorry if this is obvious but I'm really struggling here.

Any help is appreciated :)

**Comment by evantahler** [comment]
Yep, that link you found is old, and that was before we had [chat middleware](http://www.actionherojs.com/docs/#chat-middleware)!  Now we have decorators/formatters within the chat system that will (I think) do what you need.  Check the linked documentation above, and if that's nwo what you need, let me know.  

As far as the `Bye!`, I assume you are using the `socket` server?  We certainly should have a way to customize it... I've added that for you here: https://github.com/evantahler/actionhero/pull/817.  Does that work?  I still think that it is best to `ack` the quit response to the client before terminating the connection, but you can send `''` if you want now. 

You can use the localization framework now to configure that message per locale as well!

Since not that many people use the `socket` server, can you share what you are making?

Good luck!

**Comment by TombolaShepless** [comment]
@evantahler thanks for getting back so quickly! The Bye message change is bang on.

I'm investigating/prototyping a potential replacement for a C# chat server that we have started seeing performance issues with and is difficult to scale in it's current form.

I initially started out with the `chatRoom` API but I shelved it in favour of going down a manual route. This was at about 2am on Saturday so I honestly can't remember what the problems were! I've just sat here for 5 minutes trying to remember!

I'll go back to the `chatApi` this evening and let you know what issues I run into (if I do! I'm still learning action hero!)

Again, thanks for getting back so quickly!
