### ISSUE TITLE
Restrict parameters by request method (GET,POST or etc)

### ISSUE THREAD

**Issue by hzahoori** [evantahler/actionhero#818]
Looking for a feature in action hero, where I  can restrict a user to access a post method by url:
example:
post:[{path:'allUsers',action:'allUsers'}] //should only be accessible by post method, which is not the case right now.
And I should be able to configure, whether to accept data by payload or post URL(but only in post Requests) either using a rest api client(fiddler) or any service call.

Thanks

**Comment by dangerdespain** [comment]
@hzahoori - It looks like you're on the right track here. The reason that /allUsers is available through all of the methods is that "simpleRouting" is enabled. Disable that option in config/servers/web.js so that the only method of accessing that endpoint is through the routing configuration.

Regarding the payload options, you could easily create a bit of connection middleware to meet your specific use-case. Check out the docs here - http://www.actionherojs.com/docs/#connection-middleware

**Comment by dangerdespain** [comment]
More specifically, the query/body payloads can be accessed at 

data.connection.rawConnection.params = {
  query : {},
  body : {},
  files : {}
}

**Comment by hzahoori** [comment]
Great!! That worked for me!! That was the only thing I needed!! I think once the the http methods are specific to the specified routing that would solve a lot of issues.

**Comment by dangerdespain** [comment]
Fantastic! Glad that was a quick fix.
